PLAYER_NICKNAME_PATTERN = r">.+:"
RACK_PATTERN = r"[A-Z\?]{,7}"
COORDINATE_PATTERN = r"(?P<coord>[A-O0-9]{2,3})"
WORD_FORMED_PATTERN = r"(?P<word>[A-Za-z\.]{2,})"
SIGNED_SCORE_PATTERN = r"[\+-][0-9]+"
CUMULATIVE_SCORE_PATTERN = r"[0-9]+"

REGULAR_PLAY_EVENT_LINE_PATTERN = r"\s+".join([
    PLAYER_NICKNAME_PATTERN,
    RACK_PATTERN,
    COORDINATE_PATTERN,
    WORD_FORMED_PATTERN,
    SIGNED_SCORE_PATTERN,
    CUMULATIVE_SCORE_PATTERN
])

WITHDRAWN_WORD_EVENT_LINE_PATTERN = r"\s+".join([
    PLAYER_NICKNAME_PATTERN,
    RACK_PATTERN,
    "--",
    SIGNED_SCORE_PATTERN,
    CUMULATIVE_SCORE_PATTERN
])
